### ISSUE TITLE
Universal Isomorphic Support

### ISSUE THREAD

**Issue by Jaikant** [bySabi/react-scrollchor#11]
For some reason which I couldn't figure out, this doesn't work for universal isomorphic apps, the server rendering turns out to be different from the clients.

**Comment by bySabi** [comment]
Can you share server render out?
I don´t try myself universal projects yet

**Comment by Jaikant** [comment]
@bySabi Sure, give me a couple of weeks as I have moved ahead by changing my UX design temporarily. I would surely like to use this component and would try to integrate/fix the issue once I get back to this part of my UI.

**Comment by bySabi** [comment]
close this for now.
