### ISSUE TITLE
can url add hash?

### ISSUE THREAD

**Issue by jnotnull** [bySabi/react-scrollchor#13]
First, this rep is very good.

when i click the Anchor,  it scrolls very smooth.  but can url add hash? because i want to go back by the back button of browser.

**Comment by bySabi** [comment]
Go back to previous anchor position or to a different url page?

Right know react-scrollchor prevent update  of `window.location.hash` use for browser history (Back and Forward buttons). You can track it yourself using `react-scrollchor` afterAnimate callback. I'm working a major update with some improvements.

Maybe I'm don't understand your question very well but to put a different url in the anchor you will need React Router to handle it.

**Comment by bySabi** [comment]
new release, `4.0.0`, add `window.location.hash` tracking that enable back/forward button and browser history.

I'll close issue by now. Reopen is you needed it

**Comment by seb-thomas** [comment]
@bySabi  Is it possible to optionally disable this? I don't want scrolling behaviour in the browser history.

**Comment by bySabi** [comment]
@plonko I add `disableHistory` prop to new release, 4.1.0, default is `false`.

This are the current `props` https://github.com/bySabi/react-scrollchor#prop-types
