### ISSUE TITLE
React Router v4.0 usage

### ISSUE THREAD

**Issue by dzhytomyrsky** [bySabi/react-scrollchor#14]
Hello! 

Does this package work with React Router v4.0?

**Comment by bySabi** [comment]
This package is router agnostic and should don´t interfered with your React Router setup.

Remember it just render a `<a>` tag with a `onClick` event handler, a React base implementation of something like this: https://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_eff_animate_smoothscroll
