### ISSUE TITLE
Cannot resolve module 'fbjs/lib/warning'`

### ISSUE THREAD

**Issue by guven8** [bySabi/react-scrollchor#2]
I'm trying to use this package, but I'm getting this error message on import

`webpack-dev-server.js:1 ./~/react-scrollchor/lib/animatescroll.js
Module not found: Error: Cannot resolve module 'fbjs/lib/warning'`

im running 
`node v4.4.5`
`react: 15.2.0`,
`react-router: 2.4.1`,
`webpack: 1.12.9`
`webpack-dev-server: 1.14.0`

**Comment by bySabi** [comment]
On node 4 and npm 2, right?  you must install `fbjs` too:

```
npm install fbjs --save
```

With `npm 3` fbjs you don`t need add it explicitly due to Scrollchor use React provided version 

I add `fbjs` like a peerDependencie on new Scrollchor release `2.1.2`

Thanks for report it!

**Comment by bySabi** [comment]
solved with doc update.

Re-open it if not.
