### ISSUE TITLE
Scrollchor disables functionality of submit button

### ISSUE THREAD

**Issue by chasedeger88** [bySabi/react-scrollchor#20]
Not sure if you've ran into a similar problem before, but what I'm trying to do is search by location and by doing so the map will display 5 markers of breweries close by. However when I added <scrollchor> </scrollchor> around the submit button it auto scrolls but the markers don't show up anymore. Any reason for loss of functionality you could explain to me? Please and thank you!

**Comment by bySabi** [comment]
sorry! I don´t understand what is your issue.
a example repo could be useful.

**Comment by chasedeger88** [comment]
I'm sorry! Thank you for getting back to me so promptly, I really appreciate it. But I just ran a callback function and got it working. Sorry and thank you again!

**Comment by bySabi** [comment]
I do not deserve them.

Feel free to reopen this issue if you needed it
