### ISSUE TITLE
use requestAnimationFrame instead of setTimeout

### ISSUE THREAD

**Issue by kambing86** [bySabi/react-scrollchor#21]
is it better to use requestAnimationFrame instead?
https://github.com/chrisdickinson/raf

**Comment by bySabi** [comment]
`requestAnimationFrame` is better for sure!

PR is welcome 👍

**Comment by kambing86** [comment]
check https://github.com/bySabi/react-scrollchor/pull/22

**Comment by bySabi** [comment]
merged!

Thanks a ton for contrib 👍
