### ISSUE TITLE
Scrollbar jumps back and forth

### ISSUE THREAD

**Issue by xehpuk** [bySabi/react-scrollchor#25]
The scrollbar often jumps back and forth before starting the animation.

This is best explained in a short video: [react-scrollchor.mp4](https://github.com/bySabi/react-scrollchor/files/1841141/react-scrollchor.zip)

**Comment by bySabi** [comment]
@xehpuk sorry! I don't get it

**Comment by xehpuk** [comment]
There you go, with 5 fps:

![react-scrollchor](https://user-images.githubusercontent.com/3484906/37829415-2c3808fe-2e9f-11e8-9b63-ea819153111e.gif)

As you can see, the scrollbar jumps to the top of the page for one frame.

**Comment by bySabi** [comment]
In the example "Home" [Scrollchor](https://github.com/bySabi/react-scrollchor/blob/example/src/App.js#L76) has `to` set to "",   that's why, in this case, scroll jump to the top of the page. Just like will do `<a href="" ...`

**Comment by xehpuk** [comment]
It jumps to the top before scrolling from bottom to top.

**Comment by bySabi** [comment]
@xehpuk I still don't see the behaviour that you describe. Maybe is relate to your browser or default animation function, [easeOutQuad](https://github.com/bySabi/react-scrollchor/blob/master/src/scrollchor.jsx#L65)

**Comment by bySabi** [comment]
Finally I see it! 
I will investigate it.  Any help on is welcome.

**Comment by bySabi** [comment]
The example in localhost works well
Maybe is relate to github `gh-pages` hosting. I had to tweak the example a little for deploy on `gh-pages` 

Can you test it in your own server?

**Comment by bySabi** [comment]
I will close this for now.

Please, reopen it if needed.

**Comment by sohbr** [comment]
Hello. 
This issue still seems unresolved.
There is a split second flash of where it should scroll to before it actually begins scrolling.

**Comment by bySabi** [comment]
@sohbr  in what browser do you tested?

**Comment by sohbr** [comment]
This was in Chrome.

**Comment by sohbr** [comment]
I also used different easing functions and it produced the same effects.

**Comment by bySabi** [comment]
Maybe is related to this: https://github.com/bySabi/react-scrollchor/issues/30 , do you set some `offset` value on `animate` prop??
