### ISSUE TITLE
Problem Scrollchor inside <a> tag

### ISSUE THREAD

**Issue by leokrt** [bySabi/react-scrollchor#28]
Hey! I have a problem using <Scrollchor> component inside another <a> tag component. resulting in error:
> Warning:
 validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See  NavItem > SafeAnchor > a > ... > Scrollchor > a.

This happens because it is not possible to change the base component like in the bootstrap componentClass prop. Do you guys intend to adjust that?

**Comment by bySabi** [comment]
See my answer in this issue: https://github.com/bySabi/react-scrollchor/issues/17

**Comment by bySabi** [comment]
I will close this now.

Please reopen it is needed
