### ISSUE TITLE
HashRouter(react-router-dom v4) and scrollchor

### ISSUE THREAD

**Issue by jacktang** [bySabi/react-scrollchor#29]
Hello,

I use HashRouter in my react app and the landing page is single-page which use `react-scrollchor` component to scroll to some section with animation. Say I defined `#service` section in the landing page, when I click `Service` and the page scroll to the anchor and finally the URL turn to `/#/service`(should be `/#service`), the page is blank.  And I leave the example page [here](https://www.nextoken.cloud)

I searched stackover and find https://github.com/rafrex/react-router-hash-link would work, and could you support HashRouter in scrollchor?

Thanks!

**Comment by bySabi** [comment]
It seems you could solve it on example page.  The landing page is great, good job!

I don't use HashRouter my self but you can do smooth scrolling with it.

Feel free to reopen this issue is you needed.
