### ISSUE TITLE
Unknown prop `animate` on <a> tag

### ISSUE THREAD

**Issue by segnolin** [bySabi/react-scrollchor#3]
I used react-scrollchor for scrolling some hash links, everything just worked fine.
However, when I set `animate` prop to anything, the browser always pop-up the warning:

> Warning: Unknown prop `animate` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
>     in a (created by Scrollchor)
>     in Scrollchor (created by Nav)
>     in div (created by Nav)
>     in nav (created by Nav)
>     in Nav (created by Layout)
>     in div (created by Layout)
>     in Layout (created by RouterContext)
>     in RouterContext (created by Router)
>     in Router

I set the duration to 200, and it worked properly except for the warning above.
Thanks!

**Comment by bySabi** [comment]
Is fixed on new release 2.1.3, please update your project.

Thanks for report it.

Feel free to reopen this issue is not solved.
