### ISSUE TITLE
Global setup for custom animation

### ISSUE THREAD

**Issue by kspacja** [bySabi/react-scrollchor#35]
I would have animate always with offset an. Can setup custom animation globally?

**Comment by bySabi** [comment]
global setup is not implemented right now, PR are welcome. 

But can be archive easily with your own React component, for Example. (Caution!!, not tested myself)

./my-scrollchor.jsx
```
import React, { Component } from "react";
import Scrollchor from "react-scrollchor";

const OFFSET = 100 // global offset 

export function MyScrollchor(props) {
  const { children, ...props } = props;
  return <Scrollchor {...props} animate={{offset: OFFSET}}>{children}</Scrollchor>
}
```

and  ...
my-page.jsx
```
import MyScrollchor from "./my-scrollchor" as Scrollchor;
...
```

**Comment by bySabi** [comment]
I will put in the TODO list, create Wiki with some common patterns:

### Common Patterns
- [ ] Set Scrollchor settings globally
- [ ] Avoiding nested `<a>` tags using `childless` Scrollchor and `simulateClick`

**Comment by bySabi** [comment]
PR welcome
