### ISSUE TITLE
Undocumented breaking change to the API in v 7.0.0 (default export is no longer used)

### ISSUE THREAD

**Issue by cborchert** [bySabi/react-scrollchor#42]
Hi there, I think that the release notes for v 7.0.0 might need updating. 

While the documentation is clear about the fact that you need to import the component as a named export, the release notes simply say that there were no breaking changes to the API vis-à-vis v 6.0.0, and I think that adding a note about that might facilitate teams' transitions towards the new version.

Thanks so much for all your hard work!

**Comment by SeinopSys** [comment]
The note about this is present in [CHANGELOG.md](https://github.com/some-react-components/react-scrollchor/blob/v7.0.0/CHANGELOG.md) but was omitted from the release notes themselves by the looks of it. I expanded on the breaking changes sentence to hopefully make this particular breaking change clearer.

**Comment by cborchert** [comment]
Thank you so much. Now, everywhere you look, the change is explicit. Hopefully, this will help people that were in my case avoid this problem. 

I'm going to close the issue.
