### ISSUE TITLE
Not working when I put the component inside a div with overflow: scroll !

### ISSUE THREAD

**Issue by tarangdave** [bySabi/react-scrollchor#6]
When the entire component is rendered on the browser screen the Scrollchor with #id works, but when the same component is kept in a div with `overflow: scroll` property in parent div it doesn't work. 
I had the same issue with `react-scroll` [Link](https://github.com/fisshy/react-scroll).
They mentioned that `react-scroll` won't work inside a div.
Is this the same issue with `react-scrollchor`?

**Comment by bySabi** [comment]
Could you share a repo with your issue??

**Comment by bySabi** [comment]
I´m affraid this will not work cause what is scrolled is the top document container not a individual component or div. This is implemented on top of `document.documentElement` or `document.body` scrollTop, a browser use case.
See src: https://github.com/bySabi/react-scrollchor/blob/master/src/utils.js#L3

**Comment by tarangdave** [comment]
Ohk I get it.
So in my case what would you suggest?
Any other libs, within your knowledge, that would satisfy my purpose.

**Comment by bySabi** [comment]
Sorry! I don´t know any React package that do that out of box. Never need something like this.

**Comment by bySabi** [comment]
closed due inactivity
