### ISSUE TITLE
Need to scroll to anchors programmatically 

### ISSUE THREAD

**Issue by p0o** [bySabi/react-scrollchor#7]
It's not always users clicking on links in the same page but sometimes users are coming from other pages and I need to check the hash and if there were a hash scroll them to related anchor something like this:

```
componentDidMount() {
  if (location.hash) {
    schrollchor.scrollToAnchor(location.hash);
  }
}
```

**Comment by bySabi** [comment]
Well maybe utils functions could be refactored and extract an API from there.
I open to suggestions and PR are very welcome.

**Comment by edencorbin** [comment]
I'd love to see this too, got here looking to do a scrollToAnchor based on a select box selection.... which I don't think is possible, correct me if I'm wrong.

**Comment by bySabi** [comment]
Right now is not possible scrollToAnchor programmatically, utils functions are tight to the Component implementation. I'm evaluating options cause extract this functionality break Component semantics and boundaries. Maybe a separate library is more appropriate.

Still open to suggestions ...

**Comment by bySabi** [comment]
New release, `4.0.0` add some changes relate to this issue:
- tracking `window.location.hash` for enable browser history
- Childrenless component for use together with programmatically API
- update example with simulateClick API

I will close this for now. Please, reopen is needed
