### ISSUE TITLE
scrollable target should be configurable

### ISSUE THREAD

**Issue by mschipperheyn** [bySabi/react-scrollchor#9]
In my case, I have body set to 100% height with absolute div inside. I want to scroll the div, not the body

**Comment by bySabi** [comment]
This is the same request than: https://github.com/bySabi/react-scrollchor/issues/6
Is not possible at this time.

**Comment by bySabi** [comment]
PR are welcomed!

**Comment by dehypnosis** [comment]
still no progress?

**Comment by bySabi** [comment]
Still nothing about. PR are welcome on this subject.

**Comment by bySabi** [comment]
Requested feature has been implemented on release `6.0.0`. Thanks to xephuk's effort.
